# Generated by Django 4.0.1 on 2022-06-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('userpassword', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('userbirth', models.CharField(max_length=50)),
            ],
        ),
    ]
